---
apiVersion: v1
kind: Namespace
metadata:
  name: department
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: department
  name: deployment-department
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: department-app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: department-app
    spec:
      containers:
      - image: 910199971416.dkr.ecr.us-east-1.amazonaws.com/department-ecr:latest
        imagePullPolicy: Always
        name: department-app
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  namespace: department
  name: department-service
spec:
  ports:
    - port: 80
      targetPort: 5001
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: department-app
