---
apiVersion: v1
kind: Namespace
metadata:
  name: department
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: department
  name: department-config
data:
  DOMAIN: http://k8s-peoplesuitelb-da30c86c91-503852210.us-east-1.elb.amazonaws.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: department
  name: deployment-department
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: department-app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: department-app
    spec:
      containers:
      - image: 910199971416.dkr.ecr.us-east-1.amazonaws.com/department-ecr:latest
        imagePullPolicy: Always
        name: department-app
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: department-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: department
  name: department-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: department-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: department
  name: ingress-department
  annotations:
    alb.ingress.kubernetes.io/group.name: people-suite-lb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: k8s-peoplesuitelb-da30c86c91-503852210.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /peoplesuite/apis/departments
            pathType: Prefix
            backend:
              service:
                name: department-service
                port:
                  number: 80