---
apiVersion: v1
kind: Namespace
metadata:
  name: employee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: employee
  name: deployment-employee
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: employee-app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: employee-app
    spec:
      containers:
      - image: 910199971416.dkr.ecr.us-east-1.amazonaws.com/employee-ecr:latest
        imagePullPolicy: Always
        name: employee-app
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: employee
  name: employee-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: employee-app
